name: Combined deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  combined_deployment_pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fs-pokedex-main
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm ci
      - run: npm run eslint
      - run: npm run test
      - run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  tag_release:
    needs: [combined_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        if: ${{ github.event_name != 'pull' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  success_notify:
    needs: [combined_deployment_pipeline, tag_release]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' &&  success()}}
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: "Deployment Details"
          url: ${{ github.event.head_commit.url }}
          content: "Build succeeded! A new version has been deployed."
          color: 0x83d500
          description: |
            Commit: `${{ github.sha }}`
            Message: `${{ github.event.head_commit.message }}`
            Author: `${{ github.event.head_commit.author.username }}`
  failure_notify:
    needs: [combined_deployment_pipeline]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          content: "Build failed! The pipeline encountered an error."
          title: "Failure Details"
          url: ${{ github.event.head_commit.url }}
          color: 0xf70000
          description: |
            Repository: `${{ github.repository }}`
            Branch: `${{ github.ref }}`
            Commit: `${{ github.sha }}`
            Message: `${{ github.event.head_commit.message }}`
            Author: `${{ github.event.head_commit.author.username }}`
            Workflow: `${{ github.workflow }}`
            Job: `${{ github.job }}`
            [View Commit](${{ github.event.head_commit.url }})
            [Workflow Run](https://github.com/KrNor/fso-ci/actions/runs/${{ github.run_id }})
